services:
  coffee-bot:
    image: ghcr.io/lukasmandok/telegram_coffee_bot_backend:main
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_HOST=${BOT_HOST}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - DEFAULT_ADMIN=${DEFAULT_ADMIN}
      - GSHEET_SSID=${GSHEET_SSID}
      - SERVICE_ACCOUNT_EMAIL=${SERVICE_ACCOUNT_EMAIL}
      - SERVICE_ACCOUNT_PRIVATE_KEY=${SERVICE_ACCOUNT_PRIVATE_KEY}
      - PROJECT_ID=${PROJECT_ID}
      - DEBUG_MODE=${DEBUG_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - coffee-network
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: --interval 300 --cleanup
    restart: always
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge
