services:
  coffee-bot:
    image: ghcr.io/lukasmandok/telegram_coffee_bot_backend:main
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_HOST=${BOT_HOST}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_HOST=host.docker.internal
      - MONGO_PORT=${MONGO_PORT:-27017}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - coffee-network
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    restart: always
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge
